# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDial, QFrame, QGridLayout,
    QHBoxLayout, QLCDNumber, QLabel, QLayout,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSlider, QWidget)
import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 1080)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1920, 1080))
        MainWindow.setMaximumSize(QSize(1920, 1080))
        font = QFont()
        font.setFamilies([u"Piboto [Goog]"])
        font.setPointSize(12)
        font.setStyleStrategy(QFont.PreferAntialias)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/main/camera-video.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.actionExit_application = QAction(MainWindow)
        self.actionExit_application.setObjectName(u"actionExit_application")
        icon1 = QIcon()
        icon1.addFile(u":/main/application-exit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExit_application.setIcon(icon1)
        self.actionExit_application.setMenuRole(QAction.MenuRole.TextHeuristicRole)
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        icon2 = QIcon()
        icon2.addFile(u":/main/system-run.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSettings.setIcon(icon2)
        self.actionUnlock_application = QAction(MainWindow)
        self.actionUnlock_application.setObjectName(u"actionUnlock_application")
        icon3 = QIcon()
        icon3.addFile(u":/main/system-lock-screen.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionUnlock_application.setIcon(icon3)
        self.actionRebootSystem = QAction(MainWindow)
        self.actionRebootSystem.setObjectName(u"actionRebootSystem")
        icon4 = QIcon()
        icon4.addFile(u":/main/gnome-session-reboot.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRebootSystem.setIcon(icon4)
        self.actionShutdownSystem = QAction(MainWindow)
        self.actionShutdownSystem.setObjectName(u"actionShutdownSystem")
        icon5 = QIcon()
        icon5.addFile(u":/main/gnome-session-halt.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionShutdownSystem.setIcon(icon5)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Cam0FocusPlus = QPushButton(self.centralwidget)
        self.Cam0FocusPlus.setObjectName(u"Cam0FocusPlus")
        self.Cam0FocusPlus.setGeometry(QRect(770, 640, 41, 41))
        icon6 = QIcon()
        icon6.addFile(u":/main/list-add.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.Cam0FocusPlus.setIcon(icon6)
        self.Cam0FocusPlus.setIconSize(QSize(24, 24))
        self.Cam0FocusMinus = QPushButton(self.centralwidget)
        self.Cam0FocusMinus.setObjectName(u"Cam0FocusMinus")
        self.Cam0FocusMinus.setGeometry(QRect(170, 640, 41, 41))
        icon7 = QIcon()
        icon7.addFile(u":/main/list-remove.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.Cam0FocusMinus.setIcon(icon7)
        self.Cam0FocusMinus.setIconSize(QSize(24, 24))
        self.Cam0ResetROI = QPushButton(self.centralwidget)
        self.Cam0ResetROI.setObjectName(u"Cam0ResetROI")
        self.Cam0ResetROI.setGeometry(QRect(170, 700, 141, 61))
        self.Cam0TestCapture = QPushButton(self.centralwidget)
        self.Cam0TestCapture.setObjectName(u"Cam0TestCapture")
        self.Cam0TestCapture.setGeometry(QRect(340, 700, 151, 61))
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(20, 30, 940, 571))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.Cam0Grid = QGridLayout()
        self.Cam0Grid.setObjectName(u"Cam0Grid")
        self.Cam0Grid.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.Cam0CapturedValue = QLabel(self.frame)
        self.Cam0CapturedValue.setObjectName(u"Cam0CapturedValue")
        font1 = QFont()
        font1.setFamilies([u"DejaVu Sans Mono"])
        font1.setPointSize(36)
        font1.setBold(True)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.Cam0CapturedValue.setFont(font1)
        self.Cam0CapturedValue.setStyleSheet(u"")
        self.Cam0CapturedValue.setFrameShape(QFrame.Shape.Panel)
        self.Cam0CapturedValue.setFrameShadow(QFrame.Shadow.Sunken)
        self.Cam0CapturedValue.setLineWidth(2)
        self.Cam0CapturedValue.setMidLineWidth(1)
        self.Cam0CapturedValue.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.Cam0Grid.addWidget(self.Cam0CapturedValue, 1, 0, 1, 1)

        self.Cam0Source = QLabel(self.frame)
        self.Cam0Source.setObjectName(u"Cam0Source")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Cam0Source.sizePolicy().hasHeightForWidth())
        self.Cam0Source.setSizePolicy(sizePolicy1)
        self.Cam0Source.setMinimumSize(QSize(640, 480))
        self.Cam0Source.setFrameShape(QFrame.Shape.Panel)
        self.Cam0Source.setFrameShadow(QFrame.Shadow.Sunken)
        self.Cam0Source.setLineWidth(2)
        self.Cam0Source.setMidLineWidth(1)
        self.Cam0Source.setTextFormat(Qt.TextFormat.PlainText)
        self.Cam0Source.setScaledContents(True)
        self.Cam0Source.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.Cam0Grid.addWidget(self.Cam0Source, 0, 0, 1, 1)

        self.Cam0Grid.setRowStretch(0, 1)

        self.horizontalLayout.addLayout(self.Cam0Grid)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(960, 30, 940, 571))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.Cam1Grid = QGridLayout()
        self.Cam1Grid.setObjectName(u"Cam1Grid")
        self.Cam1Grid.setSizeConstraint(QLayout.SizeConstraint.SetFixedSize)
        self.Cam1CapturedValue = QLabel(self.frame_2)
        self.Cam1CapturedValue.setObjectName(u"Cam1CapturedValue")
        self.Cam1CapturedValue.setFont(font1)
        self.Cam1CapturedValue.setStyleSheet(u"")
        self.Cam1CapturedValue.setFrameShape(QFrame.Shape.Panel)
        self.Cam1CapturedValue.setFrameShadow(QFrame.Shadow.Sunken)
        self.Cam1CapturedValue.setLineWidth(2)
        self.Cam1CapturedValue.setMidLineWidth(1)
        self.Cam1CapturedValue.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.Cam1Grid.addWidget(self.Cam1CapturedValue, 1, 0, 1, 1)

        self.Cam1Source = QLabel(self.frame_2)
        self.Cam1Source.setObjectName(u"Cam1Source")
        sizePolicy1.setHeightForWidth(self.Cam1Source.sizePolicy().hasHeightForWidth())
        self.Cam1Source.setSizePolicy(sizePolicy1)
        self.Cam1Source.setMinimumSize(QSize(640, 480))
        self.Cam1Source.setFrameShape(QFrame.Shape.Panel)
        self.Cam1Source.setFrameShadow(QFrame.Shadow.Sunken)
        self.Cam1Source.setLineWidth(2)
        self.Cam1Source.setMidLineWidth(1)
        self.Cam1Source.setTextFormat(Qt.TextFormat.PlainText)
        self.Cam1Source.setScaledContents(True)
        self.Cam1Source.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.Cam1Grid.addWidget(self.Cam1Source, 0, 0, 1, 1)

        self.Cam1Grid.setRowStretch(0, 1)

        self.horizontalLayout_2.addLayout(self.Cam1Grid)

        self.Cam1ResetROI = QPushButton(self.centralwidget)
        self.Cam1ResetROI.setObjectName(u"Cam1ResetROI")
        self.Cam1ResetROI.setGeometry(QRect(1110, 700, 151, 61))
        self.Cam1FocusPlus = QPushButton(self.centralwidget)
        self.Cam1FocusPlus.setObjectName(u"Cam1FocusPlus")
        self.Cam1FocusPlus.setGeometry(QRect(1710, 640, 41, 41))
        self.Cam1FocusPlus.setIcon(icon6)
        self.Cam1FocusPlus.setIconSize(QSize(24, 24))
        self.Cam1TestCapture = QPushButton(self.centralwidget)
        self.Cam1TestCapture.setObjectName(u"Cam1TestCapture")
        self.Cam1TestCapture.setGeometry(QRect(1290, 700, 151, 61))
        self.Cam1FocusMinus = QPushButton(self.centralwidget)
        self.Cam1FocusMinus.setObjectName(u"Cam1FocusMinus")
        self.Cam1FocusMinus.setGeometry(QRect(1110, 640, 41, 41))
        self.Cam1FocusMinus.setIcon(icon7)
        self.Cam1FocusMinus.setIconSize(QSize(24, 24))
        self.Cam0Slider = QSlider(self.centralwidget)
        self.Cam0Slider.setObjectName(u"Cam0Slider")
        self.Cam0Slider.setGeometry(QRect(220, 640, 541, 41))
        self.Cam0Slider.setMaximum(320)
        self.Cam0Slider.setValue(160)
        self.Cam0Slider.setOrientation(Qt.Orientation.Horizontal)
        self.Cam0Slider.setInvertedAppearance(False)
        self.Cam0Slider.setInvertedControls(False)
        self.Cam0Slider.setTickPosition(QSlider.TickPosition.TicksBothSides)
        self.Cam1Slider = QSlider(self.centralwidget)
        self.Cam1Slider.setObjectName(u"Cam1Slider")
        self.Cam1Slider.setGeometry(QRect(1160, 640, 541, 41))
        self.Cam1Slider.setMaximum(320)
        self.Cam1Slider.setValue(160)
        self.Cam1Slider.setOrientation(Qt.Orientation.Horizontal)
        self.Cam1Slider.setInvertedAppearance(False)
        self.Cam1Slider.setInvertedControls(False)
        self.Cam1Slider.setTickPosition(QSlider.TickPosition.TicksBothSides)
        self.Frame_Error = QFrame(self.centralwidget)
        self.Frame_Error.setObjectName(u"Frame_Error")
        self.Frame_Error.setEnabled(False)
        self.Frame_Error.setGeometry(QRect(0, 10, 1921, 611))
        self.Frame_Error.setStyleSheet(u"color: red;")
        self.Frame_Error.setFrameShape(QFrame.Shape.Box)
        self.Frame_Error.setFrameShadow(QFrame.Shadow.Plain)
        self.Frame_Error.setLineWidth(30)
        self.Frame_Error.setMidLineWidth(0)
        self.StartCapture = QPushButton(self.centralwidget)
        self.StartCapture.setObjectName(u"StartCapture")
        self.StartCapture.setGeometry(QRect(580, 930, 371, 101))
        font2 = QFont()
        font2.setFamilies([u"Sans Serif"])
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setStrikeOut(False)
        font2.setStyleStrategy(QFont.PreferDefault)
        self.StartCapture.setFont(font2)
        icon8 = QIcon()
        icon8.addFile(u":/main/gtk-media-play-ltr.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.StartCapture.setIcon(icon8)
        self.StartCapture.setIconSize(QSize(24, 24))
        self.ResetError = QPushButton(self.centralwidget)
        self.ResetError.setObjectName(u"ResetError")
        self.ResetError.setEnabled(False)
        self.ResetError.setGeometry(QRect(970, 930, 371, 101))
        self.ResetError.setFont(font2)
        icon9 = QIcon()
        icon9.addFile(u":/main/gtk-delete.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.ResetError.setIcon(icon9)
        self.ResetError.setIconSize(QSize(24, 24))
        self.bTriggerManual = QPushButton(self.centralwidget)
        self.bTriggerManual.setObjectName(u"bTriggerManual")
        self.bTriggerManual.setGeometry(QRect(1620, 930, 281, 101))
        icon10 = QIcon()
        icon10.addFile(u":/main/gtk-media-record.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bTriggerManual.setIcon(icon10)
        self.bTriggerManual.setIconSize(QSize(24, 24))
        self.bStopMachine = QPushButton(self.centralwidget)
        self.bStopMachine.setObjectName(u"bStopMachine")
        self.bStopMachine.setGeometry(QRect(1620, 820, 281, 91))
        icon11 = QIcon()
        icon11.addFile(u":/main/dialog-cancel.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bStopMachine.setIcon(icon11)
        self.bStopMachine.setCheckable(False)
        self.bStopMachine.setChecked(False)
        self.bStopMachine.setFlat(False)
        self.lcdSpeed = QLCDNumber(self.centralwidget)
        self.lcdSpeed.setObjectName(u"lcdSpeed")
        self.lcdSpeed.setGeometry(QRect(130, 810, 171, 61))
        self.lcdSpeed.setFont(font)
        self.lcdSpeed.setFrameShape(QFrame.Shape.Box)
        self.lcdSpeed.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdSpeed.setLineWidth(2)
        self.lcdSpeed.setMidLineWidth(1)
        self.lcdSpeed.setSmallDecimalPoint(False)
        self.lcdSpeed.setMode(QLCDNumber.Mode.Dec)
        self.lcdSpeed.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdSpeed.setProperty(u"value", 1.126000000000000)
        self.lcdMatch = QLCDNumber(self.centralwidget)
        self.lcdMatch.setObjectName(u"lcdMatch")
        self.lcdMatch.setGeometry(QRect(130, 900, 171, 61))
        self.lcdMatch.setFont(font)
        self.lcdMatch.setFrameShape(QFrame.Shape.Box)
        self.lcdMatch.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdMatch.setLineWidth(2)
        self.lcdMatch.setMidLineWidth(1)
        self.lcdMatch.setDigitCount(8)
        self.lcdMatch.setMode(QLCDNumber.Mode.Dec)
        self.lcdMatch.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdMatch.setProperty(u"value", 12345678.000000000000000)
        self.lcdMatch.setProperty(u"intValue", 12345678)
        self.lcdErrors = QLCDNumber(self.centralwidget)
        self.lcdErrors.setObjectName(u"lcdErrors")
        self.lcdErrors.setGeometry(QRect(130, 970, 171, 61))
        self.lcdErrors.setFont(font)
        self.lcdErrors.setFrameShape(QFrame.Shape.Box)
        self.lcdErrors.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdErrors.setLineWidth(2)
        self.lcdErrors.setMidLineWidth(1)
        self.lcdErrors.setDigitCount(8)
        self.lcdErrors.setMode(QLCDNumber.Mode.Dec)
        self.lcdErrors.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdErrors.setProperty(u"value", 12345678.000000000000000)
        self.lcdErrors.setProperty(u"intValue", 12345678)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 810, 111, 51))
        font3 = QFont()
        font3.setFamilies([u"Piboto [Goog]"])
        font3.setPointSize(26)
        font3.setStyleStrategy(QFont.PreferAntialias)
        self.label.setFont(font3)
        self.label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lcdErrorsTotal = QLCDNumber(self.centralwidget)
        self.lcdErrorsTotal.setObjectName(u"lcdErrorsTotal")
        self.lcdErrorsTotal.setGeometry(QRect(310, 970, 171, 61))
        self.lcdErrorsTotal.setFont(font)
        self.lcdErrorsTotal.setStyleSheet(u"")
        self.lcdErrorsTotal.setFrameShape(QFrame.Shape.Box)
        self.lcdErrorsTotal.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdErrorsTotal.setLineWidth(2)
        self.lcdErrorsTotal.setMidLineWidth(1)
        self.lcdErrorsTotal.setDigitCount(8)
        self.lcdErrorsTotal.setMode(QLCDNumber.Mode.Dec)
        self.lcdErrorsTotal.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdErrorsTotal.setProperty(u"value", 12345678.000000000000000)
        self.lcdErrorsTotal.setProperty(u"intValue", 12345678)
        self.lcdMatchTotal = QLCDNumber(self.centralwidget)
        self.lcdMatchTotal.setObjectName(u"lcdMatchTotal")
        self.lcdMatchTotal.setGeometry(QRect(310, 900, 171, 61))
        self.lcdMatchTotal.setFont(font)
        self.lcdMatchTotal.setFrameShape(QFrame.Shape.Box)
        self.lcdMatchTotal.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdMatchTotal.setLineWidth(2)
        self.lcdMatchTotal.setMidLineWidth(1)
        self.lcdMatchTotal.setDigitCount(8)
        self.lcdMatchTotal.setMode(QLCDNumber.Mode.Dec)
        self.lcdMatchTotal.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdMatchTotal.setProperty(u"value", 12345678.000000000000000)
        self.lcdMatchTotal.setProperty(u"intValue", 12345678)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 970, 111, 51))
        self.label_2.setFont(font3)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 900, 111, 51))
        self.label_3.setFont(font3)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lcdSpeed_perminute = QLCDNumber(self.centralwidget)
        self.lcdSpeed_perminute.setObjectName(u"lcdSpeed_perminute")
        self.lcdSpeed_perminute.setGeometry(QRect(310, 810, 171, 61))
        self.lcdSpeed_perminute.setFont(font)
        self.lcdSpeed_perminute.setFrameShape(QFrame.Shape.Box)
        self.lcdSpeed_perminute.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdSpeed_perminute.setLineWidth(2)
        self.lcdSpeed_perminute.setMidLineWidth(1)
        self.lcdSpeed_perminute.setSmallDecimalPoint(False)
        self.lcdSpeed_perminute.setMode(QLCDNumber.Mode.Dec)
        self.lcdSpeed_perminute.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.lcdSpeed_perminute.setProperty(u"value", 1.126000000000000)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(160, 860, 111, 51))
        font4 = QFont()
        font4.setFamilies([u"Piboto [Goog]"])
        font4.setPointSize(19)
        font4.setStyleStrategy(QFont.PreferAntialias)
        self.label_4.setFont(font4)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(340, 860, 111, 51))
        self.label_5.setFont(font4)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(160, 770, 111, 51))
        self.label_6.setFont(font4)
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(340, 770, 111, 51))
        self.label_7.setFont(font4)
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bTimer = QPushButton(self.centralwidget)
        self.bTimer.setObjectName(u"bTimer")
        self.bTimer.setGeometry(QRect(490, 810, 61, 61))
        self.bTimer.setIcon(icon)
        self.bTimer.setIconSize(QSize(36, 36))
        self.speedDial = QDial(self.centralwidget)
        self.speedDial.setObjectName(u"speedDial")
        self.speedDial.setGeometry(QRect(560, 790, 101, 101))
        self.speedDial.setMinimum(1)
        self.speedDial.setMaximum(100)
        self.speedDial.setSliderPosition(50)
        self.speedDial.setOrientation(Qt.Orientation.Horizontal)
        self.speedDial.setInvertedAppearance(False)
        self.speedDial.setInvertedControls(False)
        self.speedDial.setWrapping(False)
        self.speedDial.setNotchTarget(4.700000000000000)
        self.speedDial.setNotchesVisible(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.Frame_Error.raise_()
        self.Cam0FocusPlus.raise_()
        self.Cam0FocusMinus.raise_()
        self.Cam0ResetROI.raise_()
        self.Cam0TestCapture.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.Cam1ResetROI.raise_()
        self.Cam1FocusPlus.raise_()
        self.Cam1TestCapture.raise_()
        self.Cam1FocusMinus.raise_()
        self.Cam0Slider.raise_()
        self.Cam1Slider.raise_()
        self.StartCapture.raise_()
        self.ResetError.raise_()
        self.bTriggerManual.raise_()
        self.bStopMachine.raise_()
        self.lcdSpeed.raise_()
        self.lcdMatch.raise_()
        self.lcdErrors.raise_()
        self.label.raise_()
        self.lcdErrorsTotal.raise_()
        self.lcdMatchTotal.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lcdSpeed_perminute.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.bTimer.raise_()
        self.speedDial.raise_()
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1920, 27))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuSystem = QMenu(self.menuFile)
        self.menuSystem.setObjectName(u"menuSystem")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionUnlock_application)
        self.menuFile.addAction(self.menuSystem.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_application)
        self.menuSystem.addAction(self.actionRebootSystem)
        self.menuSystem.addAction(self.actionShutdownSystem)

        self.retranslateUi(MainWindow)
        self.Cam0ResetROI.clicked.connect(MainWindow.ResetCamRoi)
        self.Cam0TestCapture.clicked.connect(MainWindow.TestCam)
        self.Cam0FocusMinus.clicked.connect(MainWindow.CamOnFocusButton)
        self.Cam0FocusPlus.clicked.connect(MainWindow.CamOnFocusButton)
        self.Cam1FocusPlus.clicked.connect(MainWindow.CamOnFocusButton)
        self.Cam1FocusMinus.clicked.connect(MainWindow.CamOnFocusButton)
        self.Cam1ResetROI.clicked.connect(MainWindow.ResetCamRoi)
        self.Cam1TestCapture.clicked.connect(MainWindow.TestCam)
        self.Cam0Slider.valueChanged.connect(MainWindow.CamOnFocusSlider)
        self.Cam1Slider.valueChanged.connect(MainWindow.CamOnFocusSlider)
        self.StartCapture.clicked.connect(MainWindow.StartCapturing)
        self.ResetError.clicked.connect(MainWindow.ResetError)
        self.bTriggerManual.clicked.connect(MainWindow.handle_gpiotrigger)
        self.actionExit_application.triggered.connect(MainWindow.ExitApplicationHandler)
        self.actionSettings.triggered.connect(MainWindow.SettingsHandler)
        self.actionUnlock_application.triggered.connect(MainWindow.UnlockHandler)
        self.actionRebootSystem.triggered.connect(MainWindow.RebootHandler)
        self.actionShutdownSystem.triggered.connect(MainWindow.ShutdownHandler)
        self.bStopMachine.clicked.connect(MainWindow.StartStopMachineHandler)
        self.bTimer.clicked.connect(MainWindow.TimerHandler)
        self.speedDial.valueChanged.connect(MainWindow.TimerDialHandler)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"RPICameraComparer v0.1 by CMBSolutions 2025", None))
        self.actionExit_application.setText(QCoreApplication.translate("MainWindow", u"Exit application", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.actionUnlock_application.setText(QCoreApplication.translate("MainWindow", u"Unlock application", None))
        self.actionRebootSystem.setText(QCoreApplication.translate("MainWindow", u"Reboot system", None))
        self.actionShutdownSystem.setText(QCoreApplication.translate("MainWindow", u"Shutdown system", None))
#if QT_CONFIG(tooltip)
        self.Cam0FocusPlus.setToolTip(QCoreApplication.translate("MainWindow", u"Increase focus distance", None))
#endif // QT_CONFIG(tooltip)
        self.Cam0FocusPlus.setText("")
#if QT_CONFIG(tooltip)
        self.Cam0FocusMinus.setToolTip(QCoreApplication.translate("MainWindow", u"Decrease focus distance", None))
#endif // QT_CONFIG(tooltip)
        self.Cam0FocusMinus.setText("")
#if QT_CONFIG(tooltip)
        self.Cam0ResetROI.setToolTip(QCoreApplication.translate("MainWindow", u"Reset the Region Of Interest", None))
#endif // QT_CONFIG(tooltip)
        self.Cam0ResetROI.setText(QCoreApplication.translate("MainWindow", u"Reset ROI", None))
#if QT_CONFIG(tooltip)
        self.Cam0TestCapture.setToolTip(QCoreApplication.translate("MainWindow", u"Test the capture of Camera 1", None))
#endif // QT_CONFIG(tooltip)
        self.Cam0TestCapture.setText(QCoreApplication.translate("MainWindow", u"Test capture", None))
        self.Cam0CapturedValue.setText(QCoreApplication.translate("MainWindow", u"CAM0: 00000", None))
        self.Cam0Source.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.Cam1CapturedValue.setText(QCoreApplication.translate("MainWindow", u"CAM1: 00000", None))
        self.Cam1Source.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
#if QT_CONFIG(tooltip)
        self.Cam1ResetROI.setToolTip(QCoreApplication.translate("MainWindow", u"Reset the Region Of Interest", None))
#endif // QT_CONFIG(tooltip)
        self.Cam1ResetROI.setText(QCoreApplication.translate("MainWindow", u"Reset ROI", None))
#if QT_CONFIG(tooltip)
        self.Cam1FocusPlus.setToolTip(QCoreApplication.translate("MainWindow", u"Increase focus distance", None))
#endif // QT_CONFIG(tooltip)
        self.Cam1FocusPlus.setText("")
#if QT_CONFIG(tooltip)
        self.Cam1TestCapture.setToolTip(QCoreApplication.translate("MainWindow", u"Test the capture of Camera 1", None))
#endif // QT_CONFIG(tooltip)
        self.Cam1TestCapture.setText(QCoreApplication.translate("MainWindow", u"Test capture", None))
#if QT_CONFIG(tooltip)
        self.Cam1FocusMinus.setToolTip(QCoreApplication.translate("MainWindow", u"Decrease focus distance", None))
#endif // QT_CONFIG(tooltip)
        self.Cam1FocusMinus.setText("")
        self.StartCapture.setText(QCoreApplication.translate("MainWindow", u"Start capturing", None))
        self.ResetError.setText(QCoreApplication.translate("MainWindow", u"Reset error", None))
        self.bTriggerManual.setText(QCoreApplication.translate("MainWindow", u"Manual trigger", None))
        self.bStopMachine.setText(QCoreApplication.translate("MainWindow", u"Stop machine", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Speed:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Errors:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Match:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Current", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Total", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"/min.", None))
        self.bTimer.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuSystem.setTitle(QCoreApplication.translate("MainWindow", u"System", None))
    # retranslateUi

