# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QHBoxLayout,
    QLabel, QLayout, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QSlider,
    QWidget)
import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 1080)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1920, 1080))
        MainWindow.setMaximumSize(QSize(1920, 1080))
        font = QFont()
        font.setFamilies([u"Piboto [Goog]"])
        font.setPointSize(12)
        font.setStyleStrategy(QFont.PreferAntialias)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/main/camera-video.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.actionExit_application = QAction(MainWindow)
        self.actionExit_application.setObjectName(u"actionExit_application")
        icon1 = QIcon()
        icon1.addFile(u":/main/application-exit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExit_application.setIcon(icon1)
        self.actionExit_application.setMenuRole(QAction.MenuRole.TextHeuristicRole)
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionUnlock_application = QAction(MainWindow)
        self.actionUnlock_application.setObjectName(u"actionUnlock_application")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Cam0FocusPlus = QPushButton(self.centralwidget)
        self.Cam0FocusPlus.setObjectName(u"Cam0FocusPlus")
        self.Cam0FocusPlus.setGeometry(QRect(770, 640, 41, 41))
        icon2 = QIcon()
        icon2.addFile(u":/main/list-add.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.Cam0FocusPlus.setIcon(icon2)
        self.Cam0FocusPlus.setIconSize(QSize(24, 24))
        self.Cam0FocusMinus = QPushButton(self.centralwidget)
        self.Cam0FocusMinus.setObjectName(u"Cam0FocusMinus")
        self.Cam0FocusMinus.setGeometry(QRect(170, 640, 41, 41))
        icon3 = QIcon()
        icon3.addFile(u":/main/list-remove.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.Cam0FocusMinus.setIcon(icon3)
        self.Cam0FocusMinus.setIconSize(QSize(24, 24))
        self.Cam0ResetROI = QPushButton(self.centralwidget)
        self.Cam0ResetROI.setObjectName(u"Cam0ResetROI")
        self.Cam0ResetROI.setGeometry(QRect(170, 700, 141, 61))
        self.Cam0TestCapture = QPushButton(self.centralwidget)
        self.Cam0TestCapture.setObjectName(u"Cam0TestCapture")
        self.Cam0TestCapture.setGeometry(QRect(340, 700, 151, 61))
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(20, 30, 940, 571))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout = QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.Cam0Grid = QGridLayout()
        self.Cam0Grid.setObjectName(u"Cam0Grid")
        self.Cam0Grid.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.Cam0CapturedValue = QLabel(self.frame)
        self.Cam0CapturedValue.setObjectName(u"Cam0CapturedValue")
        font1 = QFont()
        font1.setFamilies([u"DejaVu Sans Mono"])
        font1.setPointSize(36)
        font1.setBold(True)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.Cam0CapturedValue.setFont(font1)
        self.Cam0CapturedValue.setStyleSheet(u"")
        self.Cam0CapturedValue.setFrameShape(QFrame.Shape.Panel)
        self.Cam0CapturedValue.setFrameShadow(QFrame.Shadow.Sunken)
        self.Cam0CapturedValue.setLineWidth(2)
        self.Cam0CapturedValue.setMidLineWidth(1)
        self.Cam0CapturedValue.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.Cam0Grid.addWidget(self.Cam0CapturedValue, 1, 0, 1, 1)

        self.Cam0Source = QLabel(self.frame)
        self.Cam0Source.setObjectName(u"Cam0Source")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Cam0Source.sizePolicy().hasHeightForWidth())
        self.Cam0Source.setSizePolicy(sizePolicy1)
        self.Cam0Source.setMinimumSize(QSize(640, 480))
        self.Cam0Source.setFrameShape(QFrame.Shape.Panel)
        self.Cam0Source.setFrameShadow(QFrame.Shadow.Sunken)
        self.Cam0Source.setLineWidth(2)
        self.Cam0Source.setMidLineWidth(1)
        self.Cam0Source.setTextFormat(Qt.TextFormat.PlainText)
        self.Cam0Source.setScaledContents(True)
        self.Cam0Source.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.Cam0Grid.addWidget(self.Cam0Source, 0, 0, 1, 1)

        self.Cam0Grid.setRowStretch(0, 1)

        self.horizontalLayout.addLayout(self.Cam0Grid)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(960, 30, 940, 571))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.Cam1Grid = QGridLayout()
        self.Cam1Grid.setObjectName(u"Cam1Grid")
        self.Cam1Grid.setSizeConstraint(QLayout.SizeConstraint.SetFixedSize)
        self.Cam1CapturedValue = QLabel(self.frame_2)
        self.Cam1CapturedValue.setObjectName(u"Cam1CapturedValue")
        self.Cam1CapturedValue.setFont(font1)
        self.Cam1CapturedValue.setStyleSheet(u"")
        self.Cam1CapturedValue.setFrameShape(QFrame.Shape.Panel)
        self.Cam1CapturedValue.setFrameShadow(QFrame.Shadow.Sunken)
        self.Cam1CapturedValue.setLineWidth(2)
        self.Cam1CapturedValue.setMidLineWidth(1)
        self.Cam1CapturedValue.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.Cam1Grid.addWidget(self.Cam1CapturedValue, 1, 0, 1, 1)

        self.Cam1Source = QLabel(self.frame_2)
        self.Cam1Source.setObjectName(u"Cam1Source")
        sizePolicy1.setHeightForWidth(self.Cam1Source.sizePolicy().hasHeightForWidth())
        self.Cam1Source.setSizePolicy(sizePolicy1)
        self.Cam1Source.setMinimumSize(QSize(640, 480))
        self.Cam1Source.setFrameShape(QFrame.Shape.Panel)
        self.Cam1Source.setFrameShadow(QFrame.Shadow.Sunken)
        self.Cam1Source.setLineWidth(2)
        self.Cam1Source.setMidLineWidth(1)
        self.Cam1Source.setTextFormat(Qt.TextFormat.PlainText)
        self.Cam1Source.setScaledContents(True)
        self.Cam1Source.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.Cam1Grid.addWidget(self.Cam1Source, 0, 0, 1, 1)

        self.Cam1Grid.setRowStretch(0, 1)

        self.horizontalLayout_2.addLayout(self.Cam1Grid)

        self.Cam1ResetROI = QPushButton(self.centralwidget)
        self.Cam1ResetROI.setObjectName(u"Cam1ResetROI")
        self.Cam1ResetROI.setGeometry(QRect(1110, 700, 151, 61))
        self.Cam1FocusPlus = QPushButton(self.centralwidget)
        self.Cam1FocusPlus.setObjectName(u"Cam1FocusPlus")
        self.Cam1FocusPlus.setGeometry(QRect(1710, 640, 41, 41))
        self.Cam1FocusPlus.setIcon(icon2)
        self.Cam1FocusPlus.setIconSize(QSize(24, 24))
        self.Cam1TestCapture = QPushButton(self.centralwidget)
        self.Cam1TestCapture.setObjectName(u"Cam1TestCapture")
        self.Cam1TestCapture.setGeometry(QRect(1290, 700, 151, 61))
        self.Cam1FocusMinus = QPushButton(self.centralwidget)
        self.Cam1FocusMinus.setObjectName(u"Cam1FocusMinus")
        self.Cam1FocusMinus.setGeometry(QRect(1110, 640, 41, 41))
        self.Cam1FocusMinus.setIcon(icon3)
        self.Cam1FocusMinus.setIconSize(QSize(24, 24))
        self.Cam0Slider = QSlider(self.centralwidget)
        self.Cam0Slider.setObjectName(u"Cam0Slider")
        self.Cam0Slider.setGeometry(QRect(220, 640, 541, 41))
        self.Cam0Slider.setMaximum(320)
        self.Cam0Slider.setValue(160)
        self.Cam0Slider.setOrientation(Qt.Orientation.Horizontal)
        self.Cam0Slider.setInvertedAppearance(False)
        self.Cam0Slider.setInvertedControls(False)
        self.Cam0Slider.setTickPosition(QSlider.TickPosition.TicksBothSides)
        self.Cam1Slider = QSlider(self.centralwidget)
        self.Cam1Slider.setObjectName(u"Cam1Slider")
        self.Cam1Slider.setGeometry(QRect(1160, 640, 541, 41))
        self.Cam1Slider.setMaximum(320)
        self.Cam1Slider.setValue(160)
        self.Cam1Slider.setOrientation(Qt.Orientation.Horizontal)
        self.Cam1Slider.setInvertedAppearance(False)
        self.Cam1Slider.setInvertedControls(False)
        self.Cam1Slider.setTickPosition(QSlider.TickPosition.TicksBothSides)
        self.Frame_Error = QFrame(self.centralwidget)
        self.Frame_Error.setObjectName(u"Frame_Error")
        self.Frame_Error.setEnabled(False)
        self.Frame_Error.setGeometry(QRect(0, 10, 1921, 611))
        self.Frame_Error.setStyleSheet(u"color: red;")
        self.Frame_Error.setFrameShape(QFrame.Shape.Box)
        self.Frame_Error.setFrameShadow(QFrame.Shadow.Plain)
        self.Frame_Error.setLineWidth(20)
        self.Frame_Error.setMidLineWidth(0)
        self.StartCapture = QPushButton(self.centralwidget)
        self.StartCapture.setObjectName(u"StartCapture")
        self.StartCapture.setGeometry(QRect(580, 930, 371, 101))
        font2 = QFont()
        font2.setFamilies([u"Sans Serif"])
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setStrikeOut(False)
        font2.setStyleStrategy(QFont.PreferDefault)
        self.StartCapture.setFont(font2)
        icon4 = QIcon()
        icon4.addFile(u":/main/gtk-media-play-ltr.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.StartCapture.setIcon(icon4)
        self.StartCapture.setIconSize(QSize(24, 24))
        self.ResetError = QPushButton(self.centralwidget)
        self.ResetError.setObjectName(u"ResetError")
        self.ResetError.setEnabled(False)
        self.ResetError.setGeometry(QRect(970, 930, 371, 101))
        self.ResetError.setFont(font2)
        icon5 = QIcon()
        icon5.addFile(u":/main/gtk-delete.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.ResetError.setIcon(icon5)
        self.ResetError.setIconSize(QSize(24, 24))
        self.Cam0SaveCapture = QPushButton(self.centralwidget)
        self.Cam0SaveCapture.setObjectName(u"Cam0SaveCapture")
        self.Cam0SaveCapture.setGeometry(QRect(520, 700, 171, 61))
        self.bTriggerManual = QPushButton(self.centralwidget)
        self.bTriggerManual.setObjectName(u"bTriggerManual")
        self.bTriggerManual.setGeometry(QRect(1620, 930, 281, 101))
        icon6 = QIcon()
        icon6.addFile(u":/main/gtk-media-record.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bTriggerManual.setIcon(icon6)
        self.bTriggerManual.setIconSize(QSize(24, 24))
        MainWindow.setCentralWidget(self.centralwidget)
        self.Frame_Error.raise_()
        self.Cam0FocusPlus.raise_()
        self.Cam0FocusMinus.raise_()
        self.Cam0ResetROI.raise_()
        self.Cam0TestCapture.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.Cam1ResetROI.raise_()
        self.Cam1FocusPlus.raise_()
        self.Cam1TestCapture.raise_()
        self.Cam1FocusMinus.raise_()
        self.Cam0Slider.raise_()
        self.Cam1Slider.raise_()
        self.StartCapture.raise_()
        self.ResetError.raise_()
        self.Cam0SaveCapture.raise_()
        self.bTriggerManual.raise_()
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1920, 19))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionExit_application)
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionUnlock_application)

        self.retranslateUi(MainWindow)
        self.Cam0ResetROI.clicked.connect(MainWindow.ResetCamRoi)
        self.Cam0TestCapture.clicked.connect(MainWindow.TestCam)
        self.Cam0FocusMinus.clicked.connect(MainWindow.CamOnFocusButton)
        self.Cam0FocusPlus.clicked.connect(MainWindow.CamOnFocusButton)
        self.Cam1FocusPlus.clicked.connect(MainWindow.CamOnFocusButton)
        self.Cam1FocusMinus.clicked.connect(MainWindow.CamOnFocusButton)
        self.Cam1ResetROI.clicked.connect(MainWindow.ResetCamRoi)
        self.Cam1TestCapture.clicked.connect(MainWindow.TestCam)
        self.Cam0Slider.valueChanged.connect(MainWindow.CamOnFocusSlider)
        self.Cam1Slider.valueChanged.connect(MainWindow.CamOnFocusSlider)
        self.StartCapture.clicked.connect(MainWindow.StartCapturing)
        self.ResetError.clicked.connect(MainWindow.ResetError)
        self.Cam0SaveCapture.clicked.connect(MainWindow.SaveFileDialog)
        self.bTriggerManual.clicked.connect(MainWindow.handle_gpiotrigger)
        self.actionExit_application.triggered.connect(MainWindow.ExitApplicationHandler)
        self.actionSettings.triggered.connect(MainWindow.SettingsHandler)
        self.actionUnlock_application.triggered.connect(MainWindow.UnlockHandler)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"RPICameraComparer v0.1 by CMBSolutions 2025", None))
        self.actionExit_application.setText(QCoreApplication.translate("MainWindow", u"Exit application", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.actionUnlock_application.setText(QCoreApplication.translate("MainWindow", u"Unlock application", None))
#if QT_CONFIG(tooltip)
        self.Cam0FocusPlus.setToolTip(QCoreApplication.translate("MainWindow", u"Increase focus distance", None))
#endif // QT_CONFIG(tooltip)
        self.Cam0FocusPlus.setText("")
#if QT_CONFIG(tooltip)
        self.Cam0FocusMinus.setToolTip(QCoreApplication.translate("MainWindow", u"Decrease focus distance", None))
#endif // QT_CONFIG(tooltip)
        self.Cam0FocusMinus.setText("")
#if QT_CONFIG(tooltip)
        self.Cam0ResetROI.setToolTip(QCoreApplication.translate("MainWindow", u"Reset the Region Of Interest", None))
#endif // QT_CONFIG(tooltip)
        self.Cam0ResetROI.setText(QCoreApplication.translate("MainWindow", u"Reset ROI", None))
#if QT_CONFIG(tooltip)
        self.Cam0TestCapture.setToolTip(QCoreApplication.translate("MainWindow", u"Test the capture of Camera 1", None))
#endif // QT_CONFIG(tooltip)
        self.Cam0TestCapture.setText(QCoreApplication.translate("MainWindow", u"Test capture", None))
        self.Cam0CapturedValue.setText(QCoreApplication.translate("MainWindow", u"CAM0: 00000", None))
        self.Cam0Source.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.Cam1CapturedValue.setText(QCoreApplication.translate("MainWindow", u"CAM1: 00000", None))
        self.Cam1Source.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
#if QT_CONFIG(tooltip)
        self.Cam1ResetROI.setToolTip(QCoreApplication.translate("MainWindow", u"Reset the Region Of Interest", None))
#endif // QT_CONFIG(tooltip)
        self.Cam1ResetROI.setText(QCoreApplication.translate("MainWindow", u"Reset ROI", None))
#if QT_CONFIG(tooltip)
        self.Cam1FocusPlus.setToolTip(QCoreApplication.translate("MainWindow", u"Increase focus distance", None))
#endif // QT_CONFIG(tooltip)
        self.Cam1FocusPlus.setText("")
#if QT_CONFIG(tooltip)
        self.Cam1TestCapture.setToolTip(QCoreApplication.translate("MainWindow", u"Test the capture of Camera 1", None))
#endif // QT_CONFIG(tooltip)
        self.Cam1TestCapture.setText(QCoreApplication.translate("MainWindow", u"Test capture", None))
#if QT_CONFIG(tooltip)
        self.Cam1FocusMinus.setToolTip(QCoreApplication.translate("MainWindow", u"Decrease focus distance", None))
#endif // QT_CONFIG(tooltip)
        self.Cam1FocusMinus.setText("")
        self.StartCapture.setText(QCoreApplication.translate("MainWindow", u"Start capturing", None))
        self.ResetError.setText(QCoreApplication.translate("MainWindow", u"Reset error", None))
        self.Cam0SaveCapture.setText(QCoreApplication.translate("MainWindow", u"Save capture", None))
        self.bTriggerManual.setText(QCoreApplication.translate("MainWindow", u"Manual trigger", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    # retranslateUi

